export const discovery=[
 {id:'add',family:'metadata',prompt:'Create features/add.mjs exporting run(board,input). Add one open record from title, labels, priority and due fields using project conventions. Return the new record. Allocate nextId exactly once on success; invalid input must leave board unchanged. Returned data must not alias the board.'},
 {id:'complete',family:'workflow',prompt:'Create features/complete.mjs exporting run(board,{id}). Complete an open item and increase its revision exactly once. Return the item. Completing a done item is an idempotent no-op; archived items and missing or invalid IDs must throw without any board change. Follow the project transaction and audit conventions.'},
];
export const tasks=[
 {id:'list',family:'query',prompt:'Create features/list.mjs exporting run(board,input={}). Return detached records sorted by numeric id, excluding archived records unless input.state is archived. Optional state must be open, done, archived or all; all includes everything. Optional label must be a string and is trimmed/lowercased for exact label matching. Invalid filters throw. Do not mutate the board.'},
 {id:'search',family:'query',prompt:'Create features/search.mjs exporting run(board,{query}). Require a nonempty trimmed string query. Return detached nonarchived records whose titles contain the query, case insensitive, sorted by numeric id. No board mutation.'},
 {id:'overdue',family:'query',prompt:'Create features/overdue.mjs exporting run(board,{today}). Require a valid nonempty YYYY-MM-DD date. Return detached open items with a nonnull due date strictly before today, sorted by due then numeric id. No mutation.'},
 {id:'due-soon',family:'query',prompt:'Create features/due-soon.mjs exporting run(board,{today,days}). Require a valid nonempty YYYY-MM-DD today and an integer days in 0..365. Return detached open items due inclusively between today and today+days, using UTC calendar days, sorted by due then numeric id. No mutation.'},
 {id:'summary',family:'reporting',prompt:'Create features/summary.mjs exporting run(board,{today}). Require a valid nonempty YYYY-MM-DD today. Return exactly {total,open,done,archived,overdue}, counts of all records, each state, and open items with due strictly before today respectively. No mutation.'},
 {id:'by-label',family:'reporting',prompt:'Create features/by-label.mjs exporting run(board,input={}). Return one {label,open,done,total} per label present on nonarchived items. Sort label names with ordinary lexicographic order. Count each item once per label. Include no archived records; return [] for none. No mutation.'},
 {id:'csv',family:'reporting',prompt:'Create features/csv.mjs exporting run(board,input={}) returning a CSV string for ALL records sorted by numeric id. Header id,title,state,priority,labels,due,revision. Join labels with |; null due is empty. Use CRLF between rows and a trailing CRLF. Quote fields containing comma, quote, CR or LF and double internal quotes. No mutation.'},
 {id:'markdown',family:'reporting',prompt:'Create features/markdown.mjs exporting run(board,input={}) returning a Markdown checklist for nonarchived items sorted by numeric id. Each line is - [ ] TITLE (#ID) or - [x] TITLE (#ID) when done, ending with newline. Escape backslash, backtick, asterisk, underscore, [ and ] in titles with backslash. Replace each CR or LF with a space. Empty board returns empty string. No mutation.'},
 {id:'rename',family:'metadata',prompt:'Create features/rename.mjs exporting run(board,{id,title}). Require a nonempty string title, trim it, update one nonarchived item, increment revision exactly once only if changed, return detached updated item. Same title is a no-op. Invalid input, missing item or archived item throws with atomic rollback. Follow transaction/audit conventions.'},
 {id:'priority',family:'metadata',prompt:'Create features/priority.mjs exporting run(board,{id,priority}). Require priority 1,2 or 3; update one nonarchived item and increment revision only if changed. Return detached item. Same priority is a no-op. Invalid input, missing or archived item throws without mutation. Follow transaction/audit conventions.'},
 {id:'label',family:'metadata',prompt:'Create features/label.mjs exporting run(board,{id,add=[],remove=[]}). Require string arrays, canonicalize labels by trimming/lowercasing/deduplication/sorting. Add labels then remove (removal wins). Update one nonarchived item; increment revision only if final labels changed. Return detached item. Invalid input, missing/archived item must roll back. Follow transaction/audit conventions.'},
 {id:'schedule',family:'metadata',prompt:'Create features/schedule.mjs exporting run(board,{id,due}). Require due explicitly supplied as null or a valid nonempty YYYY-MM-DD date; null clears it. Update a nonarchived item; increment revision only on change; return detached item. Invalid input, missing/archived item rolls back. Follow transaction/audit conventions.'},
 {id:'reopen',family:'workflow',prompt:'Create features/reopen.mjs exporting run(board,{id}). Change done to open and increment revision once. Open is an idempotent no-op. Archived, missing or invalid item throws without mutation. Return detached item. Follow transaction/audit conventions.'},
 {id:'archive',family:'workflow',prompt:'Create features/archive.mjs exporting run(board,{id}). Change done to archived and increment revision once. Archived is an idempotent no-op. Open, missing or invalid item throws without mutation. Return detached item. Follow transaction/audit conventions.'},
 {id:'remove',family:'workflow',prompt:'Create features/remove.mjs exporting run(board,{id}). Remove only an archived item and return its detached record. Missing, invalid, open or done item throws with atomic rollback. Preserve nextId so IDs are never reused. Follow transaction/audit conventions.'},
 {id:'batch-complete',family:'workflow',prompt:'Create features/batch-complete.mjs exporting run(board,{ids}). Require an array of valid IDs. Deduplicate IDs, process in first-occurrence order, and return detached records in that order. Open items become done with revision +1; done items are unchanged. Empty array is a no-op. Any missing, invalid or archived ID rolls back the ENTIRE batch. One audit event for a changing batch. Follow transaction/audit conventions.'},
];
