'use strict';
// Generated by the UI-GATES arcade pipeline. Family implementations are spliced in at the marker.
const W = 480, H = 640, R = 8, SPEED = 320, HOLD = 0.7;

function clamp(v, lo, hi) { return Math.max(lo, Math.min(hi, v)); }
function axisInfo(p) {
  return p.axis === 'y'
    ? { n: 'y', t: 'x', nv: 'vy', tv: 'vx', ns: 'h', ts: 'w' }
    : { n: 'x', t: 'y', nv: 'vx', tv: 'vy', ns: 'w', ts: 'h' };
}
function overlaps(ball, rect) {
  const cx = clamp(ball.x, rect.x, rect.x + rect.w), cy = clamp(ball.y, rect.y, rect.y + rect.h);
  return (ball.x - cx) ** 2 + (ball.y - cy) ** 2 <= ball.r * ball.r;
}

// --- movement ---
function move(ball, dt) { ball.x += ball.vx * dt; ball.y += ball.vy * dt; }

// --- wall ---
function wall(ball, W, H) {
  if (ball.x - ball.r < 0) { ball.x = 2 * ball.r - ball.x; ball.vx = Math.abs(ball.vx); }
  else if (ball.x + ball.r > W) { ball.x = 2 * (W - ball.r) - ball.x; ball.vx = -Math.abs(ball.vx); }
  if (ball.y - ball.r < 0) { ball.y = 2 * ball.r - ball.y; ball.vy = Math.abs(ball.vy); }
}

// --- paddle ---
function paddleHit(ball, p, prev) {
  const a = axisInfo(p);
  if (ball[a.nv] * p.dir >= 0) return;                 // only balls travelling toward the paddle
  const face = p.dir < 0 ? p[a.n] : p[a.n] + p[a.ns];
  const depth = pos => -p.dir * (pos - face);          // > 0 once the centre is past the face
  let hit = overlaps(ball, p) && depth(ball[a.n]) <= p[a.ns];
  if (!hit && prev) {
    const d0 = depth(prev[a.n]), d1 = depth(ball[a.n]);
    if (d0 <= -ball.r && d1 >= -ball.r) {              // crossed the face plane this frame
      const f = (-ball.r - d0) / (d1 - d0);
      const tan = prev[a.t] + f * (ball[a.t] - prev[a.t]);
      hit = tan >= p[a.t] - ball.r && tan <= p[a.t] + p[a.ts] + ball.r;
    }
  }
  if (!hit) return;
  const off = clamp((ball[a.t] - p[a.t]) / p[a.ts] * 2 - 1, -1, 1);
  const sp = Math.hypot(ball.vx, ball.vy), ang = off * Math.PI / 3;
  ball[a.n] = face + p.dir * ball.r;
  ball[a.tv] = sp * Math.sin(ang);
  ball[a.nv] = p.dir * sp * Math.cos(ang);
}

// --- round ---
function roundCheck(state) {
  if (state.over) return;
  if (state.ball.y - state.ball.r > state.H) {
    state.lives = Math.max(0, state.lives - 1);
    if (state.lives === 0) state.over = true; else state.ball = serve(state);
  }
}

// --- brick ---
function brickHit(ball, state) {
  for (const b of state.bricks) {
    if (!b.alive || !overlaps(ball, b)) continue;
    b.alive = false; state.score += 10;
    const dx = Math.min(ball.x + ball.r - b.x, b.x + b.w - (ball.x - ball.r));
    const dy = Math.min(ball.y + ball.r - b.y, b.y + b.h - (ball.y - ball.r));
    if (dx < dy) {
      const left = ball.x < b.x + b.w / 2;
      ball.vx = left ? -Math.abs(ball.vx) : Math.abs(ball.vx);
      ball.x = left ? b.x - ball.r - 0.01 : b.x + b.w + ball.r + 0.01;   // leave the brick so a neighbour is not hit twice
    } else {
      const above = ball.y < b.y + b.h / 2;
      ball.vy = above ? -Math.abs(ball.vy) : Math.abs(ball.vy);
      ball.y = above ? b.y - ball.r - 0.01 : b.y + b.h + ball.r + 0.01;
    }
    return;
  }
}

function makeRng(seed) {
  let s = (seed >>> 0) || 1;
  return () => {
    s = (s + 0x6D2B79F5) >>> 0;
    let t = s;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function serve(state) {
  const a = -Math.PI / 2 + (state.rng() - 0.5) * 0.8;
  state.hold = HOLD;
  return {
    x: state.paddle.x + state.paddle.w / 2, y: state.paddle.y - R - 2,
    vx: Math.cos(a) * SPEED, vy: Math.sin(a) * SPEED, r: R,
  };
}

function createGame(seed) {
  const state = {
    W, H, rng: makeRng(seed), score: 0, lives: 3, over: false, won: false, hold: 0,
    paddle: { x: W / 2 - 40, y: H - 40, w: 80, h: 12, axis: 'y', dir: -1 },
    bricks: [], ball: null,
  };
  const cols = 10, rows = 6, bw = (W - 20) / cols, bh = 22;
  for (let r = 0; r < rows; r++)
    for (let c = 0; c < cols; c++)
      state.bricks.push({ x: 10 + c * bw + 2, y: 70 + r * (bh + 4), w: bw - 4, h: bh, alive: true, row: r });
  state.ball = serve(state);
  return state;
}

function step(state, dt, input) {
  if (state.over) return;
  dt = Math.min(dt, 1 / 20);
  const p = state.paddle;
  p.x = clamp(input.paddleX - p.w / 2, 0, W - p.w);
  if (state.hold > 0) {
    state.hold -= dt;
    state.ball.x = p.x + p.w / 2;
    state.ball.y = p.y - R - 2;
    return;
  }
  const b = state.ball, prev = { x: b.x, y: b.y };
  move(b, dt);
  wall(b, W, H);
  paddleHit(b, p, prev);
  brickHit(b, state);
  if (!state.bricks.some(k => k.alive)) { state.won = true; state.over = true; return; }
  roundCheck(state);
}

if (typeof document !== 'undefined') {
  const canvas = document.getElementById('game'), ctx = canvas.getContext('2d');
  canvas.width = W; canvas.height = H;
  const colors = ['#ff5d73', '#ff9a56', '#ffd166', '#6fe3a1', '#5ec8ff', '#a78bfa'];
  let state = createGame(Date.now()), paddleX = W / 2, last = performance.now();
  const keys = {};
  const toX = clientX => { const r = canvas.getBoundingClientRect(); return (clientX - r.left) * (W / r.width); };
  canvas.addEventListener('mousemove', e => { paddleX = toX(e.clientX); });
  canvas.addEventListener('touchmove', e => { paddleX = toX(e.touches[0].clientX); e.preventDefault(); }, { passive: false });
  const restart = () => { if (state.over) state = createGame(Date.now()); };
  canvas.addEventListener('click', restart);
  addEventListener('keydown', e => { keys[e.key] = true; if (e.key === ' ' || e.key === 'Enter') restart(); });
  addEventListener('keyup', e => { keys[e.key] = false; });

  function draw() {
    ctx.fillStyle = '#0d0f1a'; ctx.fillRect(0, 0, W, H);
    for (const b of state.bricks) if (b.alive) { ctx.fillStyle = colors[b.row % colors.length]; ctx.fillRect(b.x, b.y, b.w, b.h); }
    const p = state.paddle;
    ctx.fillStyle = '#e8ecff'; ctx.fillRect(p.x, p.y, p.w, p.h);
    ctx.beginPath(); ctx.arc(state.ball.x, state.ball.y, R, 0, Math.PI * 2); ctx.fillStyle = '#fff'; ctx.fill();
    ctx.fillStyle = '#9aa3c7'; ctx.font = '16px system-ui, sans-serif';
    ctx.textAlign = 'left'; ctx.fillText('Score ' + state.score, 12, 28);
    ctx.textAlign = 'right'; ctx.fillText('Lives ' + state.lives, W - 12, 28);
    if (state.over) {
      ctx.fillStyle = 'rgba(13,15,26,0.8)'; ctx.fillRect(0, 0, W, H);
      ctx.fillStyle = '#fff'; ctx.textAlign = 'center'; ctx.font = 'bold 32px system-ui, sans-serif';
      ctx.fillText(state.won ? 'YOU WIN' : 'GAME OVER', W / 2, H / 2 - 10);
      ctx.font = '16px system-ui, sans-serif'; ctx.fillText('Click or press Space to play again', W / 2, H / 2 + 22);
    }
  }
  function frame(now) {
    const dt = (now - last) / 1000; last = now;
    if (keys.ArrowLeft) paddleX -= 520 * dt;
    if (keys.ArrowRight) paddleX += 520 * dt;
    paddleX = clamp(paddleX, 0, W);
    step(state, dt, { paddleX });
    draw();
    requestAnimationFrame(frame);
  }
  window.__uigates = { get state() { return state; }, step, createGame };
  requestAnimationFrame(frame);
}

if (typeof module !== 'undefined') {
  const has = f => (typeof f === 'function' ? f : undefined);
  module.exports = {
    W, H, R, SPEED, createGame, step, serve, overlaps,
    move: has(typeof move !== 'undefined' && move), wall: has(typeof wall !== 'undefined' && wall),
    paddleHit: has(typeof paddleHit !== 'undefined' && paddleHit),
    roundCheck: has(typeof roundCheck !== 'undefined' && roundCheck),
    brickHit: has(typeof brickHit !== 'undefined' && brickHit),
  };
}
